variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'npm angular'
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@latest'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    customCommand: 'run prod-build-dev'

- task: ArchiveFiles@2
  displayName: 'archive build'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  displayName: 'publish build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
